(()=>{
const palettes=[['#0055BF','#003E8C'],['#D01012','#8E0B0D'],['#FFD500','#C8A700'],['#237841','#15512A'],['#FE8A18','#C65D00'],['#00A3DA','#00779F'],['#81007B','#560052'],['#A5CA18','#718C0F'],['#FF69B4','#C53D86'],['#6D4C41','#493129']];
const configs={
primary:{summary:'Ruta de acompañamiento para fortalecer lectura, escritura, pensamiento matemático, participación y autonomía.',chips:['Primaria','Aprendizaje activo','Seguimiento individual'],overview:'El expediente organiza una ruta de trabajo respetuosa para consolidar aprendizajes esenciales, reconocer fortalezas y desarrollar mayor seguridad al leer, escribir, resolver problemas y explicar ideas.',strengths:[{title:'Comprensión',text:'Reconoce información relevante y relaciona ideas con experiencias cercanas.'},{title:'Pensamiento lógico',text:'Construye estrategias para resolver actividades y problemas.'},{title:'Participación',text:'Comparte ideas, escucha y colabora durante las actividades.'},{title:'Potencial de autonomía',text:'Puede avanzar con rutinas claras, práctica y acompañamiento positivo.'}],priorities:[{title:'Lectura comprensiva',text:'Identificar ideas principales, secuencias, personajes y detalles.'},{title:'Pensamiento matemático',text:'Resolver operaciones y problemas mediante procedimientos claros.'},{title:'Expresión escrita',text:'Organizar ideas en oraciones y textos breves comprensibles.'},{title:'Autonomía',text:'Seguir instrucciones, revisar el trabajo y explicar respuestas.'}],route:[{title:'Reconocer',text:'Identificar conocimientos previos y estrategias útiles.'},{title:'Practicar',text:'Trabajar con actividades breves, visuales y significativas.'},{title:'Aplicar',text:'Usar lo aprendido en nuevos retos y situaciones.'},{title:'Compartir',text:'Explicar avances y reunir evidencias del proceso.'}],goals:[{title:'Comprender mejor',text:'Leer e interpretar textos con mayor claridad.'},{title:'Resolver con estrategia',text:'Elegir procedimientos y revisar resultados.'},{title:'Expresar ideas',text:'Comunicar de forma oral, escrita y creativa.'},{title:'Ganar confianza',text:'Participar y trabajar con mayor autonomía.'}],badges:['📚 Lector curioso','🧩 Constructor de soluciones','🤝 Trabajo en equipo','🌱 En crecimiento'],familyMessage:'El acompañamiento familiar puede centrarse en una rutina breve de lectura, juegos matemáticos cotidianos y preguntas que permitan explicar cómo resolvió una actividad. Conviene reconocer el esfuerzo y evitar comparaciones.',evidence:['Comprensión lectora','Pensamiento matemático','Producción escrita','Participación']},
transition:{summary:'Preparación integral para cerrar primaria e iniciar secundaria con bases, hábitos y confianza.',chips:['Transición a Secundaria','Consolidación','Nuevos hábitos'],overview:'La ruta se enfoca en consolidar los aprendizajes indispensables de primaria y desarrollar estrategias de organización, comprensión y razonamiento que faciliten el ingreso a secundaria.',strengths:[{title:'Experiencia escolar',text:'Cuenta con aprendizajes que pueden organizarse y aprovecharse como base.'},{title:'Capacidad de análisis',text:'Puede relacionar datos, instrucciones y situaciones cuando trabaja paso a paso.'},{title:'Participación',text:'Tiene oportunidades para comunicar ideas y colaborar.'},{title:'Potencial de transición',text:'Puede ganar seguridad con metas breves y seguimiento constante.'}],priorities:[{title:'Comprensión de consignas',text:'Interpretar instrucciones y textos con vocabulario académico.'},{title:'Matemáticas esenciales',text:'Consolidar operaciones, fracciones, proporcionalidad y problemas.'},{title:'Organización',text:'Planear tareas, administrar tiempos y revisar avances.'},{title:'Comunicación',text:'Explicar procedimientos y redactar respuestas completas.'}],route:[{title:'Diagnosticar',text:'Reconocer bases firmes y contenidos prioritarios.'},{title:'Consolidar',text:'Practicar aprendizajes esenciales de primaria.'},{title:'Organizar',text:'Construir hábitos y estrategias de estudio.'},{title:'Transitar',text:'Prepararse para las exigencias de secundaria.'}],goals:[{title:'Cerrar primaria con bases',text:'Consolidar aprendizajes indispensables.'},{title:'Comprender instrucciones',text:'Interpretar consignas con mayor autonomía.'},{title:'Estudiar con método',text:'Mantener una rutina breve y organizada.'},{title:'Ingresar con confianza',text:'Enfrentar la nueva etapa con mejores herramientas.'}],badges:['🎯 Preparación','🧠 Pensamiento crítico','📚 Hábitos de estudio','🚀 Nueva etapa'],familyMessage:'La familia puede apoyar con horarios breves, metas semanales y revisión de pendientes sin resolver las tareas por el estudiante. La transición mejora cuando se reconocen avances concretos y se fomenta la responsabilidad.',evidence:['Lectura y consignas','Matemáticas esenciales','Organización','Proyecto de transición']},
secondary:{summary:'Ruta de fortalecimiento para desarrollar comprensión, razonamiento, organización y autonomía en secundaria.',chips:['Secundaria','Pensamiento crítico','Seguimiento individual'],overview:'El expediente prioriza habilidades transversales para secundaria: comprender información, argumentar, resolver problemas, organizar tareas y aplicar conocimientos en situaciones reales.',strengths:[{title:'Pensamiento crítico',text:'Puede analizar información y construir opiniones fundamentadas.'},{title:'Aplicación práctica',text:'Aprende mejor cuando relaciona conceptos con situaciones reales.'},{title:'Colaboración',text:'Cuenta con oportunidades para comunicar ideas y trabajar en equipo.'},{title:'Potencial de autonomía',text:'Puede mejorar su desempeño con planificación y seguimiento.'}],priorities:[{title:'Comprensión y argumentación',text:'Interpretar textos, distinguir ideas y justificar respuestas.'},{title:'Razonamiento matemático',text:'Resolver problemas, proporcionalidad, álgebra y geometría.'},{title:'Ciencias y entorno',text:'Interpretar datos, explicar fenómenos y formular conclusiones.'},{title:'Hábitos académicos',text:'Planear, cumplir entregas, revisar y pedir apoyo oportunamente.'}],route:[{title:'Ubicar',text:'Identificar conocimientos y necesidades prioritarias.'},{title:'Recuperar',text:'Fortalecer bases mediante práctica guiada.'},{title:'Aplicar',text:'Resolver retos, problemas y proyectos.'},{title:'Autonomizar',text:'Trabajar con organización y menor dependencia.'}],goals:[{title:'Comprender y argumentar',text:'Explicar ideas con evidencia y claridad.'},{title:'Resolver problemas',text:'Organizar datos y procedimientos.'},{title:'Aplicar ciencias',text:'Relacionar conceptos con el entorno.'},{title:'Mejorar hábitos',text:'Estudiar con constancia y planificación.'}],badges:['🧠 Pensador crítico','🔬 Explorador científico','🤝 Colaboración','🎯 Meta activa'],familyMessage:'El acompañamiento más útil consiste en acordar horarios, revisar que comprenda las instrucciones y pedirle que explique sus decisiones. Es preferible valorar la constancia y la mejora personal antes que comparar resultados.',evidence:['Comprensión y argumentación','Razonamiento matemático','Ciencias','Proyecto aplicado']},
medium:{summary:'Ruta académica para fortalecer bases, organización, autonomía y preparación para el Nivel Medio Superior.',chips:['Nivel Medio Superior','Plan individual','Autonomía'],overview:'El expediente integra una estrategia de recuperación y avance centrada en comprensión, pensamiento matemático, comunicación académica, uso responsable de tecnología y hábitos sostenibles de estudio.',strengths:[{title:'Experiencia y criterio',text:'Puede relacionar aprendizajes escolares con decisiones y situaciones reales.'},{title:'Tecnología aplicada',text:'Puede aprovechar herramientas digitales para investigar, organizar y crear.'},{title:'Capacidad de recuperación',text:'Con metas concretas puede fortalecer bases y avanzar de manera visible.'},{title:'Autonomía en desarrollo',text:'Puede asumir mayor responsabilidad sobre tiempos, tareas y objetivos.'}],priorities:[{title:'Comprensión académica',text:'Interpretar textos, instrucciones, argumentos y fuentes.'},{title:'Matemáticas y lógica',text:'Consolidar álgebra, funciones, geometría y resolución de problemas.'},{title:'Comunicación',text:'Redactar, presentar y defender ideas con claridad.'},{title:'Gestión del estudio',text:'Planear semanas, dividir tareas y evaluar el propio avance.'}],route:[{title:'Diagnosticar',text:'Definir bases, metas y contenidos prioritarios.'},{title:'Recuperar',text:'Consolidar conocimientos indispensables.'},{title:'Profundizar',text:'Aplicar conceptos en problemas y proyectos.'},{title:'Proyectar',text:'Construir hábitos y objetivos para continuar estudiando.'}],goals:[{title:'Fortalecer bases',text:'Recuperar aprendizajes necesarios para avanzar.'},{title:'Resolver con autonomía',text:'Elegir estrategias y verificar resultados.'},{title:'Comunicar mejor',text:'Presentar ideas de forma clara y estructurada.'},{title:'Gestionar el tiempo',text:'Trabajar con planificación y constancia.'}],badges:['🚀 Progreso','💻 Tecnología','🧠 Estrategia','🎓 Proyecto académico'],familyMessage:'En esta etapa conviene acordar metas y tiempos, respetar la autonomía del estudiante y revisar avances en momentos definidos. El acompañamiento debe promover responsabilidad, diálogo y decisiones informadas.',evidence:['Comprensión académica','Matemáticas y lógica','Proyecto tecnológico','Organización personal']},
english:{summary:'Programa individual para desarrollar comprensión, pronunciación, vocabulario y confianza comunicativa en inglés.',chips:['Programa de Inglés','Comunicación','Práctica constante'],overview:'La ruta combina escucha, pronunciación, lectura, vocabulario y conversación mediante actividades breves. El objetivo es usar el idioma con mayor seguridad, no memorizar listas aisladas.',strengths:[{title:'Disposición comunicativa',text:'Puede avanzar mediante conversaciones breves y situaciones reales.'},{title:'Aprendizaje auditivo',text:'La escucha guiada favorece pronunciación y comprensión.'},{title:'Vocabulario funcional',text:'Puede incorporar expresiones útiles en contextos cotidianos.'},{title:'Constancia',text:'La práctica frecuente permite avances sostenidos.'}],priorities:[{title:'Listening',text:'Comprender instrucciones, preguntas y mensajes breves.'},{title:'Speaking',text:'Responder y participar con frases cada vez más completas.'},{title:'Pronunciation',text:'Mejorar sonidos, ritmo y claridad al hablar.'},{title:'Reading and vocabulary',text:'Comprender textos breves y ampliar vocabulario útil.'}],route:[{title:'Escuchar',text:'Reconocer sonidos y expresiones frecuentes.'},{title:'Repetir',text:'Practicar pronunciación con apoyo.'},{title:'Usar',text:'Aplicar frases en diálogos y situaciones.'},{title:'Comunicar',text:'Participar con mayor seguridad y autonomía.'}],goals:[{title:'Comprender mensajes',text:'Seguir instrucciones y preguntas breves.'},{title:'Hablar con confianza',text:'Usar expresiones funcionales.'},{title:'Mejorar pronunciación',text:'Hablar con mayor claridad.'},{title:'Leer y aprender vocabulario',text:'Interpretar textos breves.'}],badges:['🌎 English Explorer','🎧 Listening','💬 Speaking','⭐ Constancia'],familyMessage:'La práctica puede reforzarse con canciones, videos breves, lectura en voz alta y conversaciones sencillas. Lo importante es usar el idioma con frecuencia y reconocer cada intento de comunicación.',evidence:['Listening','Speaking','Pronunciation','Reading']}
};
function make(name,stage,type,index,extra={}){const c=configs[type];return{name,stage,summary:extra.summary||c.summary,chips:extra.chips||c.chips,colors:palettes[index%palettes.length],overview:extra.overview||c.overview,strengths:extra.strengths||c.strengths,priorities:extra.priorities||c.priorities,route:c.route,goals:c.goals,badges:extra.badges||c.badges,familyMessage:c.familyMessage,evidence:c.evidence};}
window.EXPEDIENTES={
demo:make('Expediente de ejemplo','Nivel escolar','primary',0),
melissa:make('Melissa Cumplido López','Primaria','primary',1),
amayai:make('Amayai Ivonne Garza Zaragoza','Primaria','primary',2),
tabita:make('Tabita Dorcas Gamboa Valor','Primaria','primary',3),
christopher:make('Christopher Rebolledo Díaz','Primaria','primary',4),
santiago:make('Santiago Merino Roque','Primaria','primary',5),
noel:make('Noel Amado Santibáñez Velasco','Primaria','primary',6),
dana:make('Dana Lisseth Bolaños Quintero','Primaria','primary',7),
tamara:make('Tamara Beltrán Rivera','Primaria','primary',8),
blanca:make('Blanca Marlen Lucas Bolaños','6.º de Primaria','transition',9),
felix:make('Félix Miguel Thiago Zacarías','3.º de Primaria','primary',0,{chips:['Primaria','Constancia','Exploración científica'],badges:['⭐ Constancia','🔬 Explorador científico','🤝 Trabajo responsable','📚 Lector curioso']}),
aylen:make('Aylen López Bravo','Primaria','primary',1,{chips:['Primaria','Participación','Empatía'],badges:['📚 Participación lectora','🤝 Empatía','🚀 Progreso constante','🎨 Creatividad']}),
isabela:make('Isabela Bartolo Hilario','Primaria','primary',2,{chips:['Primaria','Curiosidad','Pensamiento lógico']}),
jatzibe:make('Jatzibe Guadalupe Galo Manuel','4.º de Primaria','primary',3,{chips:['Primaria','Creatividad','Lectura']}),
alitzel:make('Alitzel del Pilar Manuel Manuel','2.º de Primaria','primary',4),
betzaida:make('Betzaida Beltrán Roque','Primaria','primary',5),
benito:make('Benito Bolaños Matías','Primaria','primary',6),
aranza:make('Aranza José Carrillo','Primaria','primary',7,{chips:['Primaria','Consolidación','Hábitos de estudio']}),
angel:make('Ángel Leonel Gamboa Bartolo','Transición a Secundaria','transition',8,{chips:['Transición a Secundaria','Pensamiento científico','Resolución de problemas']}),
rosalia:make('Rosalía Estrada Narciso','2.º de Primaria','primary',9,{chips:['Primaria','Lectora en crecimiento','Responsabilidad','Creatividad'],badges:['📖 Lectora curiosa','🎨 Creatividad','🌱 En crecimiento','🤝 Participación']}),
anahi:make('Anahí Bartolo Hilario','Secundaria','secondary',0,{chips:['Secundaria','Convivencia positiva','Fortaleciendo hábitos']}),
emmanuel:make('Emmanuel Cohetero Morales','Ingreso a Secundaria','transition',1),
iker:make('Iker Alexander Manzano Díaz','2.º de Secundaria','secondary',2),
ana:make('Ana Díaz Lobato','Secundaria','secondary',3),
yaremi:make('Yaremi José Carrillo','Secundaria','secondary',4),
irving:make('Irving Fernando Merino Roque','3.º de Secundaria','secondary',5,{chips:['3.º de Secundaria','Tecnología aplicada','Preparación para Medio Superior'],badges:['💻 Tecnología','🧠 Pensamiento crítico','🔬 Ciencias','🎯 Transición']}),
beltran:make('Alumno(a) Beltrán','2.º de Secundaria · Nombre por confirmar','secondary',6,{summary:'Expediente provisional pendiente de confirmar el nombre completo del estudiante.'}),
juanpablo:make('Juan Pablo Manuel Manzano','Nivel Medio Superior','medium',7),
felipe:make('Felipe de Jesús Cumplido Morales','Nivel Medio Superior','medium',8),
heder:make('Heder Omar','Nivel Medio Superior','medium',9),
henry:make('Henry Sánchez','Programa individual de Inglés','english',0)
};
})();