const $=id=>document.getElementById(id);
const state={student:null,b:0,q:0,teacher:false,answers:{},order:{}};
const key=(b,q)=>b+"-"+q;
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function save(){localStorage.setItem("misionLeer150",JSON.stringify({student:state.student,answers:state.answers,order:state.order}))}
function load(){try{let x=JSON.parse(localStorage.getItem("misionLeer150")||"null");if(x){state.student=x.student;state.answers=x.answers||{};state.order=x.order||{}}}catch(e){}}
function speak(text,rate=.85){if(!("speechSynthesis" in window)){alert("Este navegador no tiene lectura de voz.");return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text||"");u.lang="es-MX";u.rate=rate;speechSynthesis.speak(u)}
function stats(b){let a=Object.entries(state.answers).filter(([k])=>k.startsWith(b+"-"));return{done:a.length,correct:a.filter(([,v])=>v.correct).length}}
function begin(){let name=$("studentName").value.trim();if(!name){alert("Escribe el nombre.");return}state.student={name,age:$("age").value||"No indicada",grade:$("grade").value||"No indicado",teacher:$("teacherName").value.trim()||"No indicado"};save();showBlocks()}
function showBlocks(){$("startScreen").classList.add("hidden");$("quizScreen").classList.add("hidden");$("reportScreen").classList.add("hidden");$("blockScreen").classList.remove("hidden");$("welcome").textContent="Hola, "+state.student.name+". Elige una misión";$("blockGrid").innerHTML="";blocks.forEach((b,i)=>{let s=stats(i),x=document.createElement("button");x.className="block-card";x.innerHTML='<div class="icon">'+b.icon+'</div><h3>Bloque '+(i+1)+' · '+b.name+'</h3><p>'+b.subtitle+'</p><p style="margin-top:14px;font-weight:900;color:#17324d">'+s.done+'/50 respondidos · '+s.correct+' aciertos</p><p style="margin-top:10px;font-size:.9rem">Toca esta tarjeta para comenzar</p>';x.onclick=()=>openBlock(i);$("blockGrid").appendChild(x)})}
function openBlock(i){state.b=i;let first=blocks[i].activities.findIndex((_,q)=>!state.answers[key(i,q)]);state.q=first<0?0:first;$("blockScreen").classList.add("hidden");$("quizScreen").classList.remove("hidden");render()}
function opts(){let k=key(state.b,state.q);if(!state.order[k])state.order[k]=shuffle(blocks[state.b].activities[state.q].options);return state.order[k]}
function render(){let a=blocks[state.b].activities[state.q],old=state.answers[key(state.b,state.q)],s=stats(state.b);state.started=Date.now();$("counter").textContent="Bloque "+(state.b+1)+" · Reto "+(state.q+1)+" de 50";$("score").textContent=s.correct+" aciertos";$("bar").style.width=(state.q/50*100)+"%";$("level").textContent=blocks[state.b].icon+" "+blocks[state.b].name+" · "+a.skill;$("title").textContent=a.title;$("instruction").textContent=a.instruction;$("prompt").textContent=a.prompt||"Escucha con atención";$("teacherNote").innerHTML="<strong>Apoyo docente:</strong> "+a.tip+"<br><strong>Respuesta:</strong> "+a.answer;$("feedback").textContent="";$("feedback").className="feedback";$("options").innerHTML="";opts().forEach(o=>{let x=document.createElement("button");x.className="option";x.textContent=o;if(old){x.disabled=true;if(o===a.answer)x.classList.add("correct");else if(o===old.selected)x.classList.add("wrong")}x.onclick=()=>answer(x,o);$("options").appendChild(x)});if(old){$("feedback").textContent=old.correct?"¡Muy bien! ⭐":"Observa la respuesta correcta.";$("feedback").className="feedback "+(old.correct?"good":"bad")}$("nextBtn").textContent=state.q===49?"Ver informe →":"Siguiente →";document.body.classList.toggle("teacher-on",state.teacher)}
function answer(btn,o){let a=blocks[state.b].activities[state.q],k=key(state.b,state.q);if(state.answers[k])return;let correct=o===a.answer;state.answers[k]={selected:o,correct};[...$("options").children].forEach(x=>x.disabled=true);btn.classList.add(correct?"correct":"wrong");if(!correct)[...$("options").children].forEach(x=>{if(x.textContent===a.answer)x.classList.add("correct")});$("feedback").textContent=correct?"¡Excelente! ⭐":"No pasa nada. Observa y vuelve a leer.";$("feedback").className="feedback "+(correct?"good":"bad");speak(correct?"Muy bien":"No pasa nada. Observa la respuesta correcta.");save()}
function next(){if(!state.answers[key(state.b,state.q)]){alert("Selecciona una respuesta.");return}if(state.q<49){state.q++;render();scrollTo({top:0,behavior:"smooth"})}else report()}
function report(){$("quizScreen").classList.add("hidden");$("reportScreen").classList.remove("hidden");let b=blocks[state.b],s=stats(state.b),pct=Math.round(s.correct/50*100),skills={};b.activities.forEach((a,i)=>{skills[a.skill]??={t:0,c:0};skills[a.skill].t++;if(state.answers[key(state.b,i)]?.correct)skills[a.skill].c++});let tiles=Object.entries(skills).map(([n,x])=>{let p=Math.round(x.c/x.t*100),mood=p>=80?"🌟":p>=60?"🙂":"🧩",moodClass=p>=80?"good":p>=60?"mid":"low",label=p>=80?"Dominado":p>=60?"En proceso":"Necesita práctica",fill=p>=80?"var(--green)":p>=60?"#d49a1d":"var(--red)";return '<div class="skill-tile"><div class="skill-face '+moodClass+'">'+mood+'</div><div><strong>'+n+'</strong><small>'+label+' · '+p+'%</small><div class="skill-mini-track"><div class="skill-mini-fill" style="width:'+p+'%;background:'+fill+'"></div></div></div></div>'}).join("");let status=pct>=80?"¡Gran avance!":pct>=60?"Va por buen camino":"Necesita más acompañamiento",face=pct>=80?"🏆":pct>=60?"👏":"💪";$("report").innerHTML='<span class="badge">'+b.icon+' Informe visual del bloque '+(state.b+1)+'</span><h2>'+state.student.name+'</h2><p class="helper">'+b.name+' · '+state.student.grade+' · '+state.student.age+' años</p><div class="visual-summary"><div class="donut-wrap"><div class="donut" style="--pct:'+pct+'"><div class="donut-content"><strong>'+pct+'%</strong><span>avance</span></div></div><h3 style="margin:14px 0 4px">'+face+' '+status+'</h3><div class="visual-legend"><div class="legend-chip green">🌟 Dominado</div><div class="legend-chip yellow">🙂 En proceso</div><div class="legend-chip red">🧩 Practicar</div></div></div><div><h3 style="margin-top:0">Mapa rápido de habilidades</h3><p class="helper">Cada tarjeta muestra visualmente cómo va el alumno.</p><div class="skill-tiles">'+tiles+'</div></div></div><div class="metric-grid"><div class="metric"><small>Aciertos</small><strong>'+s.correct+'/50</strong></div><div class="metric"><small>Resultado</small><strong>'+pct+'%</strong></div><div class="metric"><small>Respondidos</small><strong>'+s.done+'/50</strong></div><div class="metric"><small>Aplicador</small><strong style="font-size:1rem">'+state.student.teacher+'</strong></div></div><div class="section callout">Practiquen de 10 a 15 minutos. No comparen, no regañen y permitan que el niño lea despacio. Este resultado es orientativo y no sustituye una valoración profesional.</div><div class="author-credit"><strong>Material elaborado por Luis Alberto Antonio Narciso</strong><span>Diseño educativo, evaluación y experiencia interactiva para el aprendizaje lector.</span><br><a href="https://narciso1516.github.io/narcisotesting.com/" target="_blank" rel="noopener noreferrer">🌐 Visitar sitio del autor</a></div>'}
load();$("startBtn").onclick=begin;$("teacherBtn").onclick=()=>{state.teacher=!state.teacher;document.body.classList.toggle("teacher-on",state.teacher);$("teacherBtn").textContent=state.teacher?"Ocultar modo docente":"Modo docente"};$("resetBtn").onclick=()=>{if(confirm("¿Borrar todo el progreso?")){localStorage.removeItem("misionLeer150");location.reload()}};$("listenBtn").onclick=()=>{let a=blocks[state.b].activities[state.q];speak(a.say||a.prompt,.85)};$("slowBtn").onclick=()=>{let a=blocks[state.b].activities[state.q];speak(a.say||a.prompt,.58)};$("blocksBtn").onclick=showBlocks;$("returnBtn").onclick=showBlocks;$("nextBtn").onclick=next;if(state.student){$("studentName").value=state.student.name||"";$("age").value=state.student.age==="No indicada"?"":state.student.age||"";$("grade").value=state.student.grade||"";$("teacherName").value=state.student.teacher==="No indicado"?"":state.student.teacher||""}