const questions=[
["Comprensión literal","📚","Ubicación y contexto","¿Dónde y en qué época ocurre la leyenda?",["En Córdoba, Veracruz, durante la Nueva España","En Xalapa durante la Revolución Mexicana","En Puebla durante la Independencia"],0],
["Comprensión literal","📚","Tradición oral","¿Por qué la historia de la Mulata sigue viva?",["Porque se publicó como noticia","Porque fue transmitida por tradición oral","Porque existe una grabación de la época"],1],
["Comprensión literal","📚","Caracterización","¿Por qué era reconocida la Mulata?",["Por su inteligencia y conocimientos sobre plantas medicinales","Por ser dueña de barcos","Por trabajar como guardia"],0],
["Comprensión literal","📚","Rumores","¿Qué aseguraban algunas personas sobre ella?",["Que nunca envejecía y realizaba brujería","Que había fundado Córdoba","Que era una autoridad colonial"],0],
["Comprensión literal","📚","Desenlace","¿Qué encontraron al abrir la celda?",["A la Mulata dormida","El barco pintado en la pared","Una puerta secreta"],1],
["Comprensión inferencial","🔎","Causas","¿Por qué la envidia pudo favorecer las acusaciones?",["Porque algunas personas podían convertir su admiración en resentimiento","Porque la envidia siempre demuestra un delito","Porque las autoridades la pidieron"],0],
["Comprensión inferencial","🔎","Actitud del personaje","¿Qué muestra la tranquilidad de la Mulata ante la sentencia?",["Que confiaba en que la verdad era más fuerte que los rumores","Que no comprendía lo que sucedía","Que estaba de acuerdo con su encarcelamiento"],0],
["Comprensión inferencial","🔎","Símbolos","¿Qué simboliza principalmente el barco?",["La libertad frente a la injusticia","La riqueza del puerto","Una prueba contra la Mulata"],0],
["Comprensión inferencial","🔎","Permanencia cultural","¿Por qué la historia ha permanecido durante tantos años?",["Porque combina misterio, valores y memoria colectiva","Porque todas las personas creen literalmente en la magia","Porque fue escrita por las autoridades"],0],
["Comprensión inferencial","🔎","Relación causa-consecuencia","¿Qué permitió que un rumor terminara en una condena?",["La falta de pruebas y de pensamiento crítico","La existencia de un barco verdadero","El conocimiento de plantas medicinales"],0],
["Análisis narrativo","🧩","Hechos y fantasía","¿Cuál elemento es claramente fantástico?",["La desaparición al subir al barco dibujado","La existencia de la ciudad de Córdoba","El uso de plantas medicinales"],0],
["Análisis narrativo","🧩","Estructura","¿Cuál acontecimiento funciona como clímax de la leyenda?",["La desaparición de la Mulata en el barco","La explicación del contexto histórico","La mención de las plantas"],0],
["Análisis narrativo","🧩","Ambiente","¿Qué efecto produce la celda cerrada y el barco en la pared?",["Refuerza el misterio del desenlace","Demuestra que todo fue una noticia","Elimina el elemento fantástico"],0],
["Análisis narrativo","🧩","Voz narrativa","La expresión «según la leyenda» indica que:",["El narrador presenta un relato tradicional, no una prueba histórica","El narrador presenció los hechos","Todo lo narrado fue comprobado científicamente"],0],
["Pensamiento crítico","⚖️","Pruebas y acusaciones","¿Cuál fue el mayor error de las autoridades?",["Encarcelarla sin reunir pruebas suficientes","Permitirle dibujar","Escuchar al guardia"],0],
["Pensamiento crítico","⚖️","Distinción conceptual","¿Cuál opción es una creencia y no un hecho comprobado?",["Que realizaba actos de brujería","Que vivía en Córdoba","Que conocía plantas medicinales"],0],
["Pensamiento crítico","⚖️","Argumentación","¿Qué argumento cuestiona mejor la condena?",["Una acusación repetida no se convierte en verdad sin evidencias","La mayoría siempre tiene razón","Los rumores son suficientes si causan miedo"],0],
["Pensamiento crítico","⚖️","Fuentes confiables","Para investigar una acusación, sería necesario:",["Comparar testimonios, buscar pruebas y escuchar a la persona acusada","Elegir el rumor más popular","Castigar primero e investigar después"],0],
["Reflexión ética y social","💬","Prejuicios","¿Qué relación existe entre prejuicio e injusticia en el texto?",["El prejuicio llevó a juzgarla por su origen y reputación","El prejuicio ayudó a encontrar pruebas","No existe relación entre ambos"],0],
["Reflexión ética y social","💬","Ciudadanía digital","¿Qué conducta actual se relaciona con la enseñanza de la leyenda?",["Verificar información antes de compartirla en redes","Compartir acusaciones para obtener reacciones","Creer una publicación porque muchas personas la repiten"],0],
["Reflexión ética y social","💬","Responsabilidad colectiva","¿Quiénes contribuyeron a la injusticia?",["Quienes inventaron, difundieron o aceptaron rumores sin comprobarlos","Solamente la Mulata","Únicamente el barco dibujado"],0],
["Reflexión ética y social","💬","Derechos","¿Qué derecho fue ignorado cuando la encarcelaron sin pruebas?",["El derecho a un trato justo y a ser considerada inocente mientras no se demuestre lo contrario","El derecho a navegar","El derecho a ser famosa"],0],
["Síntesis y creatividad","✨","Síntesis","¿Cuál resume mejor la leyenda?",["Una mujer admirada y envidiada es condenada sin pruebas y escapa de forma fantástica, dejando una reflexión sobre prejuicios y rumores","Una médica construye un barco real y viaja a otro país","Una autoridad investiga un caso y demuestra todas las acusaciones"],0],
["Síntesis y creatividad","✨","Final alternativo","¿Qué final alternativo conserva mejor el mensaje central?",["Las autoridades investigan, reconocen que no hay pruebas y reparan la injusticia","La ciudad prohíbe las plantas medicinales","Los rumores se vuelven ley sin discusión"],0],
["Síntesis y creatividad","✨","Aplicación","¿Qué lema representa mejor el aprendizaje de la lectura?",["Antes de juzgar, investiga; antes de compartir, comprueba","Si todos lo dicen, debe ser verdad","La apariencia revela la verdad"],0]
];
let current=0,student="",grade="",attempts=1,errors=0,errorLog=[],highestReached=1;
const $=id=>document.getElementById(id);
$("modalStory").innerHTML=document.querySelector(".storyCard .story").innerHTML;
$("start").onclick=()=>{student=$("name").value.trim();grade=$("grade").value;if(!student){alert("Escribe el nombre del alumno o alumna.");return}$("registration").classList.add("hidden");$("quiz").classList.remove("hidden");renderQuestion()};
function renderQuestion(){const q=questions[current];$("stage").textContent=q[0];$("icon").textContent=q[1];$("skill").textContent=q[2];$("counter").textContent=`Pregunta ${current+1} de ${questions.length}`;$("attempt").textContent=`Intento actual: ${attempts}`;$("bar").style.width=`${current/questions.length*100}%`;$("question").textContent=q[3];$("feedback").textContent="";$("feedback").className="feedback";$("options").innerHTML="";q[4].forEach((text,index)=>{const b=document.createElement("button");b.className="option";b.textContent=`${String.fromCharCode(65+index)}) ${text}`;b.onclick=()=>checkAnswer(index,b);$("options").appendChild(b)})}
function checkAnswer(selected,button){const q=questions[current],correct=q[5];document.querySelectorAll(".option").forEach(b=>b.disabled=true);highestReached=Math.max(highestReached,current+1);if(selected===correct){button.classList.add("correct");$("feedback").textContent="¡Correcto! Continúa con el siguiente desafío.";$("feedback").className="feedback ok";current++;$("bar").style.width=`${current/questions.length*100}%`;setTimeout(()=>current===questions.length?showResult():renderQuestion(),650)}else{button.classList.add("wrong");errorLog.push({attempt:attempts,questionNumber:current+1,level:q[0],skill:q[2],question:q[3],selected:q[4][selected],correct:q[4][correct]});errors++;attempts++;$("feedback").textContent="Respuesta incorrecta. Volverás a la pregunta 1.";$("feedback").className="feedback bad";setTimeout(()=>{current=0;renderQuestion()},1300)}}
function showResult(){$("quiz").classList.add("hidden");$("result").classList.remove("hidden");$("student").textContent=student;$("gradeResult").textContent=grade;$("tries").textContent=attempts;$("errors").textContent=errors;$("highest").textContent=highestReached;$("date").textContent=new Date().toLocaleDateString("es-MX",{year:"numeric",month:"long",day:"numeric"});$("history").innerHTML=errorLog.length?errorLog.map(r=>`<div class="history-item"><div class="history-top"><span>Intento ${r.attempt}</span><span>Pregunta ${r.questionNumber}</span></div><p><strong>${r.question}</strong></p><div class="small">${r.level} · ${r.skill}</div><div class="wrong-text"><strong>Respondió:</strong> ${r.selected}</div><div class="right-text"><strong>Respuesta correcta:</strong> ${r.correct}</div></div>`).join(""):'<div class="summary"><strong>Sin errores.</strong><p class="small">La evaluación se completó correctamente en el primer intento.</p></div>';const groups=["Comprensión literal","Comprensión inferencial","Análisis narrativo","Pensamiento crítico","Reflexión ética y social","Síntesis y creatividad"];$("skills").innerHTML=groups.map(g=>{const misses=errorLog.filter(r=>r.level===g).length;let label="🟢 Dominio sólido",cls="green";if(misses>=2){label="🟡 En desarrollo";cls="yellow"}if(misses>=4){label="🔴 Requiere refuerzo";cls="red"}return `<div class="skill-card"><strong>${g}</strong><div class="mini"><span style="width:${Math.max(35,100-Math.min(65,misses*15))}%"></span></div><div class="traffic ${cls}">${label}</div><div class="small">${misses} errores registrados</div></div>`}).join("");$("teacherReport").textContent=errors===0?"El alumno presenta dominio sólido de las habilidades evaluadas.":errors<=3?"El alumno alcanzó el dominio completo con pocos reinicios. Conviene revisar las preguntas registradas.":"Se recomienda reforzar lectura analítica, identificación de evidencias y pensamiento crítico.";$("familyReport").textContent=errors===0?"Comprendió la lectura con claridad y reflexionó correctamente sobre prejuicios, injusticia y rumores.":"Completó la actividad con perseverancia. Revisen juntos las preguntas donde tuvo dificultades.";window.scrollTo({top:$("result").offsetTop-10,behavior:"smooth"})}
function restart(){location.reload()}function openReading(){$("readingModal").classList.remove("hidden")}function closeReading(){$("readingModal").classList.add("hidden")}
