const $ = (s) => document.querySelector(s);
const avatars = ['🦊','🐯','🐼','🦉','🐙','🦁','🐸','🦄','🐵','🐺'];
let selectedAvatar = avatars[0];
const ladders = {4:10, 9:16, 15:22, 24:31, 30:36};
const snakes = {13:8, 20:14, 28:21, 35:29, 38:33};
const memoryDeck = [
{id:'m1',prompt:'Observa con atención. Más adelante te preguntaré algo sobre estas tarjetas.',items:[{symbol:'7',color:'#ff6b7a'},{symbol:'3',color:'#5de2a8'},{symbol:'9',color:'#5b7cff'}],recall:{question:'¿De qué color era el número 3?',options:['Rojo','Verde','Azul','Amarillo'],answer:'Verde',explain:'El número 3 estaba en color verde.'}},
{id:'m2',prompt:'Memoriza las figuras y sus colores. No necesitas escribir nada.',items:[{symbol:'★',color:'#ffd166'},{symbol:'▲',color:'#ff6b7a'},{symbol:'●',color:'#4ed7f1'}],recall:{question:'¿Qué figura era roja?',options:['La estrella','El triángulo','El círculo','Ninguna'],answer:'El triángulo',explain:'El triángulo era la figura roja.'}},
{id:'m3',prompt:'Mira el orden. Después tendrás que recuperarlo de memoria.',items:[{symbol:'🌙',color:'#cdbdff'},{symbol:'☀️',color:'#ffd166'},{symbol:'🌎',color:'#5de2a8'}],recall:{question:'¿Qué objeto estaba en medio?',options:['La Luna','El Sol','La Tierra','Una estrella'],answer:'El Sol',explain:'El Sol estaba en la tarjeta central.'}},
{id:'m4',prompt:'Última prueba de observación. Fíjate en los tres números.',items:[{symbol:'12',color:'#ff77be'},{symbol:'4',color:'#4ed7f1'},{symbol:'18',color:'#ffd166'}],recall:{question:'¿Qué número estaba pintado de amarillo?',options:['12','4','18','8'],answer:'18',explain:'El número 18 era amarillo.'}}
];
const commonQuestions=[
{cat:'🇲🇽 Historia',q:'¿Quién dio el famoso Grito de Dolores que inició la Independencia de México?',opts:['Miguel Hidalgo','Benito Juárez','Francisco Villa','Sor Juana'],a:'Miguel Hidalgo',e:'Miguel Hidalgo dio el Grito de Dolores en 1810.'},
{cat:'🌎 Cultura general',q:'¿Cuál es el planeta más cercano al Sol?',opts:['Venus','Mercurio','Tierra','Marte'],a:'Mercurio',e:'Mercurio es el planeta más cercano al Sol.'},
{cat:'🧠 Lógica',q:'Completa la secuencia: 2, 4, 6, 8, ...',opts:['9','10','11','12'],a:'10',e:'La secuencia aumenta de dos en dos.'},
{cat:'🇲🇽 Historia',q:'¿Qué ocurrió primero en la historia de México?',opts:['La Independencia','La Revolución Mexicana','La llegada a la Luna','Los Juegos Olímpicos de 1968'],a:'La Independencia',e:'La Independencia comenzó en 1810; la Revolución Mexicana inició en 1910.'},
{cat:'🌿 Naturaleza',q:'¿Qué gas tomamos principalmente del aire para respirar?',opts:['Oxígeno','Helio','Hidrógeno','Vapor'],a:'Oxígeno',e:'Nuestro cuerpo necesita oxígeno para vivir.'},
{cat:'🌎 Geografía',q:'¿Cuál es el océano más grande de la Tierra?',opts:['Atlántico','Pacífico','Índico','Ártico'],a:'Pacífico',e:'El océano Pacífico es el más grande.'},
{cat:'🏛️ Historia',q:'¿Qué civilización construyó Chichén Itzá?',opts:['Maya','Romana','Vikinga','Egipcia'],a:'Maya',e:'Chichén Itzá fue una importante ciudad de la civilización maya.'},
{cat:'🔤 Lenguaje',q:'¿Cuál palabra está escrita correctamente?',opts:['Árbol','Arvol','Hárbol','Árvol'],a:'Árbol',e:'“Árbol” se escribe con b y lleva tilde.'},
{cat:'🐾 Ciencia',q:'¿Cuál de estos animales es un mamífero?',opts:['Delfín','Tiburón','Pulpo','Tortuga'],a:'Delfín',e:'El delfín respira aire y alimenta a sus crías con leche.'},
{cat:'🌎 Geografía',q:'¿En qué continente se encuentra México?',opts:['América','Europa','Asia','África'],a:'América',e:'México forma parte de América del Norte.'},
{cat:'🇲🇽 Cultura',q:'¿Cuál de estos alimentos tiene origen mesoamericano?',opts:['Maíz','Sushi','Pasta italiana','Croissant'],a:'Maíz',e:'El maíz fue domesticado en Mesoamérica hace miles de años.'},
{cat:'🧠 Lógica',q:'Si hoy es martes, ¿qué día será dentro de dos días?',opts:['Miércoles','Jueves','Viernes','Domingo'],a:'Jueves',e:'Después del martes viene miércoles y luego jueves.'}
];
const byLevel={small:[
{cat:'➕ Matemáticas',q:'María tiene 5 estrellas y gana 3 más. ¿Cuántas tiene ahora?',opts:['6','7','8','9'],a:'8',e:'5 + 3 = 8.'},
{cat:'🔍 Comparación',q:'¿Qué número es mayor?',opts:['27','72','Son iguales','No se puede saber'],a:'72',e:'72 tiene 7 decenas y 27 tiene 2 decenas.'},
{cat:'🌈 Naturaleza',q:'¿Qué necesita una planta para crecer?',opts:['Agua y luz','Solo juguetes','Solo sombra','Refresco'],a:'Agua y luz',e:'Las plantas necesitan agua, luz y nutrientes.'},
{cat:'🧠 Lógica',q:'🐶 🐱 🐶 🐱 🐶 ... ¿qué sigue?',opts:['🐱','🐶','🐭','🐰'],a:'🐱',e:'El patrón alterna perro y gato.'}],medium:[
{cat:'➗ Matemáticas',q:'Si repartes 24 monedas entre 6 exploradores por igual, ¿cuántas recibe cada uno?',opts:['3','4','5','6'],a:'4',e:'24 ÷ 6 = 4.'},
{cat:'🔍 Comparación',q:'¿Cuál fracción representa una cantidad mayor?',opts:['1/2','1/4','1/8','1/10'],a:'1/2',e:'Cuando el numerador es 1, un denominador menor representa una parte mayor.'},
{cat:'🇲🇽 Historia',q:'¿Cuál era una de las grandes ciudades mexicas cuando llegaron los españoles?',opts:['Tenochtitlan','París','Atenas','Tokio'],a:'Tenochtitlan',e:'México-Tenochtitlan fue la capital del imperio mexica.'},
{cat:'🧠 Lógica',q:'Un reloj marca las 3:00. ¿Cuántas horas faltan para las 6:00?',opts:['2','3','4','6'],a:'3',e:'De las 3 a las 6 transcurren tres horas.'}],big:[
{cat:'📐 Matemáticas',q:'¿Cuál es el resultado de 3 × (4 + 2)?',opts:['14','18','20','24'],a:'18',e:'Primero 4 + 2 = 6; después 3 × 6 = 18.'},
{cat:'🔍 Comparación',q:'¿Cuál número decimal es mayor?',opts:['0.7','0.67','0.607','0.07'],a:'0.7',e:'0.7 equivale a 0.70, que es mayor que 0.67.'},
{cat:'🇲🇽 Historia',q:'¿En qué siglo comenzó la Independencia de México?',opts:['Siglo XVIII','Siglo XIX','Siglo XX','Siglo XXI'],a:'Siglo XIX',e:'Comenzó en 1810, que pertenece al siglo XIX.'},
{cat:'🧠 Lógica',q:'Si todos los jaguares son felinos y Luna es un jaguar, ¿qué podemos afirmar?',opts:['Luna es felino','Luna es ave','Luna es pez','No sabemos nada'],a:'Luna es felino',e:'Si todos los jaguares pertenecen al grupo de los felinos, Luna también.'}]};
let state={name:'',avatar:selectedAvatar,level:'medium',pos:1,score:0,correct:0,answered:0,streak:0,bestStreak:0,memoryCorrect:0,memoryAsked:0,step:0,challengeIndex:0,memories:{},finished:false};
const missionPlan=[{type:'q'},{type:'memoryStore',mem:0},{type:'q'},{type:'q'},{type:'memoryRecall',mem:0},{type:'q'},{type:'memoryStore',mem:1},{type:'q'},{type:'q'},{type:'memoryRecall',mem:1},{type:'q'},{type:'memoryStore',mem:2},{type:'q'},{type:'q'},{type:'memoryRecall',mem:2},{type:'q'},{type:'memoryStore',mem:3},{type:'q'},{type:'q'},{type:'memoryRecall',mem:3},{type:'q'},{type:'q'},{type:'q'},{type:'q'}];
let questionQueue=[];
function buildAvatars(){ $('#avatars').innerHTML=avatars.map((a,i)=>`<button class="avatar ${i===0?'active':''}" data-a="${a}" aria-label="Elegir ${a}">${a}</button>`).join('');document.querySelectorAll('.avatar').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.avatar').forEach(x=>x.classList.remove('active'));btn.classList.add('active');selectedAvatar=btn.dataset.a;})); }
function shuffled(arr){return [...arr].sort(()=>Math.random()-.5)}
function buildQueue(){questionQueue=shuffled([...commonQuestions,...byLevel[state.level]]).slice(0,16)}
function buildBoard(){const board=$('#board');board.innerHTML='';let rows=[];for(let r=0;r<8;r++){let start=36-r*5;let row=[start,start+1,start+2,start+3,start+4];if(r%2===0)row.reverse();rows.push(row)}rows.flat().forEach(n=>{const c=document.createElement('div');c.className='cell'+(ladders[n]?' special-ladder':'')+(snakes[n]?' special-snake':'')+(n===40?' finish':'');c.dataset.n=n;c.innerHTML=`<span>${n}</span>${ladders[n]?'<span class="mini">🪜</span>':''}${snakes[n]?'<span class="mini">🐍</span>':''}${n===40?'<span class="mini">🏆</span>':''}`;board.appendChild(c)});updateToken()}
function updateToken(){document.querySelectorAll('.cell').forEach(c=>{c.classList.remove('current');const t=c.querySelector('.token');if(t)t.remove()});const cell=document.querySelector(`.cell[data-n="${state.pos}"]`);if(!cell)return;cell.classList.add('current');const t=document.createElement('div');t.className='token';t.textContent=state.avatar;cell.appendChild(t);$('#posLabel').textContent=state.pos;$('#scoreLabel').textContent=state.score;$('#streakLabel').textContent=state.streak;$('#progressBar').style.width=`${Math.max(2,(state.pos/40)*100)}%`;updateWorld();save()}
function updateWorld(){const p=state.pos;let w='🌿 Selva del Inicio';if(p>=9)w='🏺 Ruinas del Tiempo';if(p>=17)w='🌋 Paso del Volcán';if(p>=25)w='🔭 Observatorio Secreto';if(p>=33)w='🏰 Fortaleza del Tesoro';$('#worldName').textContent=w;$('#missionLabel').textContent=`Misión ${Math.min(state.challengeIndex+1,missionPlan.length)} de ${missionPlan.length}`}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function save(){localStorage.setItem('tesoroExpedicionV1',JSON.stringify(state))}
function clearSave(){localStorage.removeItem('tesoroExpedicionV1')}
function start(){const name=$('#playerName').value.trim();if(!name){toast('Escribe tu nombre o apodo para comenzar.');return}state={...state,name,avatar:selectedAvatar,level:$('#level').value};buildQueue();$('#topAvatar').textContent=state.avatar;$('#topName').textContent=state.name;$('#miniPlayerName').textContent=state.name;$('#startScreen').classList.remove('active');$('#gameScreen').classList.add('active');buildBoard();save()}
function openChallenge(){if(state.finished)return;const item=missionPlan[state.challengeIndex];if(!item){finish();return}if(item.type==='memoryStore')return showMemoryStore(item.mem);if(item.type==='memoryRecall')return showMemoryRecall(item.mem);showQuestion()}
function showQuestion(){let q=questionQueue[state.step%questionQueue.length];state.step++;renderQuestion(q,false)}
function renderQuestion(q,isMemory){const options=shuffled(q.opts||q.options);$('#sheet').innerHTML=`<span class="qtag">${isMemory?'🧠 Memoria':q.cat}</span><h3 class="question" id="questionTitle">${q.q||q.question}</h3>${isMemory?'<div class="context">Sin volver atrás: recuerda lo que viste varios retos antes.</div>':''}<div class="options">${options.map(o=>`<button class="option" data-value="${escapeHtml(o)}"><span>${o}</span><span>›</span></button>`).join('')}</div><div class="feedback" id="feedback"></div><button class="continue" id="continueBtn">Continuar en el mapa →</button>`;$('#challengeModal').classList.add('show');document.querySelectorAll('.option').forEach(btn=>btn.addEventListener('click',()=>answer(btn,q,isMemory)))}
function answer(btn,q,isMemory){if(document.querySelector('.option.locked'))return;const value=btn.dataset.value,answer=q.a||q.answer,correct=value===answer;document.querySelectorAll('.option').forEach(b=>b.classList.add('locked'));btn.classList.add(correct?'correct':'wrong');const fb=$('#feedback');fb.className='feedback show '+(correct?'ok':'no');if(correct){state.correct++;state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak);const gain=isMemory?160:100;state.score+=gain;fb.innerHTML=`✅ <b>¡Correcto!</b> +${gain} puntos. ${q.e||q.explain||''}`;if(isMemory)state.memoryCorrect++}else{state.streak=0;state.score=Math.max(0,state.score-25);fb.innerHTML=`✨ <b>Respuesta registrada.</b> -25 puntos. ${q.e||q.explain||''}`}if(isMemory)state.memoryAsked++;state.answered++;$('#continueBtn').classList.add('show');$('#continueBtn').onclick=()=>{$('#challengeModal').classList.remove('show');advance(correct,isMemory)};save()}
function showMemoryStore(index){const m=memoryDeck[index];state.memories[m.id]=true;$('#sheet').innerHTML=`<span class="qtag">👁️ Misión de observación</span><h3 class="question">Guarda esta pista en tu memoria</h3><div class="memory-stage"><p style="color:var(--muted)">${m.prompt}</p><div class="memory-grid">${m.items.map(it=>`<div class="memory-item"><div class="num" style="color:${it.color}">${it.symbol}</div></div>`).join('')}</div><div class="memory-timer"><i></i></div><p style="font-size:.8rem;color:#9eb1d4">La pista desaparecerá en 6 segundos…</p></div>`;$('#challengeModal').classList.add('show');setTimeout(()=>{if(!$('#challengeModal').classList.contains('show'))return;$('#sheet').innerHTML=`<span class="qtag">🧠 Pista guardada</span><h3 class="question">¡Listo! Sigue avanzando.</h3><div class="context">No te diré cuándo volverá esta información. Tu memoria será parte del tesoro.</div><button class="continue show" id="continueMemory">Regresar al mapa →</button>`;$('#continueMemory').onclick=()=>{$('#challengeModal').classList.remove('show');state.challengeIndex++;moveBy(2,'👁️ Observación completada: +2 casillas')}},6100)}
function showMemoryRecall(index){const m=memoryDeck[index];const q={...m.recall,cat:'🧠 Memoria'};renderQuestion(q,true)}
function advance(correct,isMemory){state.challengeIndex++;let spaces=correct?(isMemory?4:3):1;moveBy(spaces,correct?`✨ ${spaces} casillas por tu respuesta`:'🧭 Sigues en la expedición: +1 casilla')}
function moveBy(spaces,msg){const target=Math.min(40,state.pos+spaces);let cur=state.pos;const timer=setInterval(()=>{cur++;state.pos=cur;updateToken();if(cur>=target){clearInterval(timer);setTimeout(()=>resolveSpecial(msg),250)}},170)}
function resolveSpecial(msg){if(ladders[state.pos]){const from=state.pos;state.pos=ladders[from];state.score+=50;updateToken();toast(`🪜 ¡Atajo! ${from} → ${state.pos} · +50 puntos`)}else if(snakes[state.pos]){const from=state.pos;state.pos=snakes[from];state.score=Math.max(0,state.score-30);updateToken();toast(`🐍 Trampa: ${from} → ${state.pos}`)}else toast(msg);if(state.pos>=40||state.challengeIndex>=missionPlan.length){setTimeout(finish,900)}else{$('#cardTitle').textContent=nextCardTitle();$('#cardText').textContent=nextCardText();$('#cardEyebrow').textContent=`Misión ${state.challengeIndex+1}`;updateWorld();save()}}
function nextCardTitle(){const item=missionPlan[state.challengeIndex];if(!item)return'El tesoro te espera';if(item.type==='memoryStore')return'👁️ Cámara de observación';if(item.type==='memoryRecall')return'🧠 El templo recuerda';return['Una puerta antigua','El puente del conocimiento','La brújula pregunta','Una inscripción misteriosa'][state.challengeIndex%4]}
function nextCardText(){const item=missionPlan[state.challengeIndex];if(item?.type==='memoryStore')return'Mira con atención: esta pista volverá más adelante.';if(item?.type==='memoryRecall')return'Recupera un detalle que viste varios retos atrás.';return'Responde una sola vez. Tu decisión moverá la ficha por el mapa.'}
function finish(){state.finished=true;state.pos=Math.min(40,Math.max(state.pos,38));$('#gameScreen').classList.remove('active');$('#resultScreen').classList.add('active');const memPct=state.memoryAsked?Math.round(state.memoryCorrect/state.memoryAsked*100):0;$('#finalScore').textContent=state.score;$('#finalCorrect').textContent=`${state.correct}/${state.answered}`;$('#finalMemory').textContent=memPct+'%';$('#finalStreak').textContent=state.bestStreak;$('#finalPos').textContent=state.pos;$('#resultMessage').textContent=`${state.name}, completaste una expedición de memoria, historia, cultura general y lógica.`;$('#secretCode').textContent=makeCode();save()}
function makeCode(){const animals=['JAGUAR','QUETZAL','AXOLOTE','PUMA','AGUILA'];let n=(state.score+state.correct*17+state.name.length*31)%900+100;return `${animals[state.name.length%animals.length]}-${n}`}
function escapeHtml(str){return String(str).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
$('#startBtn').addEventListener('click',start);$('#challengeBtn').addEventListener('click',openChallenge);$('#copyBtn').addEventListener('click',async()=>{const text=`🏆 ${state.name} completó El Tesoro Perdido con ${state.score} puntos. Código: ${$('#secretCode').textContent}`;try{await navigator.clipboard.writeText(text);toast('Resultado copiado. Ya puedes pegarlo en WhatsApp.')}catch{toast('No se pudo copiar automáticamente. Mantén presionado el código.')}});$('#restartBtn').addEventListener('click',()=>{clearSave();location.reload()});
function restore(){const raw=localStorage.getItem('tesoroExpedicionV1');if(!raw)return;try{const old=JSON.parse(raw);if(!old.name)return;if(old.finished){state=old;$('#startScreen').classList.remove('active');$('#resultScreen').classList.add('active');const memPct=state.memoryAsked?Math.round(state.memoryCorrect/state.memoryAsked*100):0;$('#finalScore').textContent=state.score;$('#finalCorrect').textContent=`${state.correct}/${state.answered}`;$('#finalMemory').textContent=memPct+'%';$('#finalStreak').textContent=state.bestStreak;$('#finalPos').textContent=state.pos;$('#resultMessage').textContent=`${state.name}, completaste una expedición de memoria, historia, cultura general y lógica.`;$('#secretCode').textContent=makeCode();return}state=old;buildQueue();$('#startScreen').classList.remove('active');$('#gameScreen').classList.add('active');$('#topAvatar').textContent=state.avatar;$('#topName').textContent=state.name;$('#miniPlayerName').textContent=state.name;buildBoard();$('#cardTitle').textContent=nextCardTitle();$('#cardText').textContent=nextCardText();toast('🧭 Recuperamos tu expedición guardada.')}catch(e){clearSave()}}
buildAvatars();restore();
