const $=s=>document.querySelector(s);
const avatars=['🦊','🐯','🐼','🦉','🐙','🦁','🐸','🦄','🐵','🐺'];let selectedAvatar=avatars[0];
const ladders={4:10,9:16,15:22,24:31,30:36},snakes={13:8,20:14,28:21,35:29,38:33};
const memoryDeck=[
{id:'m1',prompt:'Observa con atención. Más adelante te preguntaré algo sobre estas tarjetas.',items:[['7','#ff6b7a'],['3','#5de2a8'],['9','#5b7cff']],recall:{q:'¿De qué color era el número 3?',opts:['Rojo','Verde','Azul','Amarillo'],a:'Verde',e:'El 3 era verde.'}},
{id:'m2',prompt:'Memoriza las figuras y sus colores.',items:[['★','#ffd166'],['▲','#ff6b7a'],['●','#4ed7f1']],recall:{q:'¿Qué figura era roja?',opts:['La estrella','El triángulo','El círculo','Ninguna'],a:'El triángulo',e:'El triángulo era rojo.'}},
{id:'m3',prompt:'Mira el orden. Después tendrás que recuperarlo.',items:[['🌙','#cdbdff'],['☀️','#ffd166'],['🌎','#5de2a8']],recall:{q:'¿Qué objeto estaba en medio?',opts:['La Luna','El Sol','La Tierra','Una estrella'],a:'El Sol',e:'El Sol estaba en medio.'}},
{id:'m4',prompt:'Fíjate en números y colores.',items:[['12','#ff77be'],['4','#4ed7f1'],['18','#ffd166']],recall:{q:'¿Qué número estaba amarillo?',opts:['12','4','18','8'],a:'18',e:'El 18 era amarillo.'}},
{id:'m5',prompt:'Recuerda el orden de estos animales.',items:[['🐢','#5de2a8'],['🦜','#ff6b7a'],['🐬','#4ed7f1']],recall:{q:'¿Qué animal apareció primero?',opts:['La tortuga','El loro','El delfín','El jaguar'],a:'La tortuga',e:'La tortuga estaba primero.'}},
{id:'m6',prompt:'Observa número, forma y posición.',items:[['◆ 5','#cdbdff'],['● 8','#ffd166'],['▲ 2','#ff6b7a']],recall:{q:'¿Qué número acompañaba al círculo?',opts:['2','5','8','10'],a:'8',e:'El círculo llevaba el 8.'}}
];
const fixed=[
['🇲🇽 Historia','¿Quién dio el Grito de Dolores que inició la Independencia de México?',['Miguel Hidalgo','Benito Juárez','Francisco Villa','Sor Juana'],'Miguel Hidalgo','Miguel Hidalgo encabezó el llamado de 1810.'],
['🇲🇽 Historia','¿En qué año inició la Independencia de México?',['1810','1910','1821','2010'],'1810','Comenzó en 1810.'],
['🇲🇽 Historia','¿En qué año inició la Revolución Mexicana?',['1910','1810','1921','1968'],'1910','Comenzó en 1910.'],
['🇲🇽 Historia','¿Qué ocurrió primero?',['Independencia de México','Revolución Mexicana','Llegada a la Luna','Juegos Olímpicos de México'],'Independencia de México','La Independencia inició en 1810.'],
['🇲🇽 Historia','¿Qué civilización construyó Chichén Itzá?',['Maya','Romana','Vikinga','Egipcia'],'Maya','Chichén Itzá fue una ciudad maya.'],
['🇲🇽 Historia','¿Cuál fue la capital del imperio mexica?',['Tenochtitlan','Palenque','Monte Albán','Teotihuacan'],'Tenochtitlan','México-Tenochtitlan fue la capital mexica.'],
['🇲🇽 Historia','¿Quién es conocido como el Benemérito de las Américas?',['Benito Juárez','Miguel Hidalgo','Emiliano Zapata','José María Morelos'],'Benito Juárez','Ese título se asocia con Benito Juárez.'],
['🇲🇽 Historia','¿Quién escribió “Los Sentimientos de la Nación”?',['José María Morelos','Miguel Hidalgo','Porfirio Díaz','Francisco I. Madero'],'José María Morelos','Morelos presentó el documento en 1813.'],
['🇲🇽 Cultura','¿Cuál de estos alimentos tiene origen mesoamericano?',['Maíz','Sushi','Croissant','Pizza'],'Maíz','El maíz fue domesticado en Mesoamérica.'],
['🇲🇽 Cultura','¿Qué se celebra tradicionalmente el 1 y 2 de noviembre en México?',['Día de Muertos','Año Nuevo','Pascua','San Patricio'],'Día de Muertos','Es una tradición mexicana de memoria y homenaje.'],
['🇲🇽 Cultura','¿Qué lengua indígena dio palabras como “chocolate” y “tomate” al español?',['Náhuatl','Latín','Francés','Japonés'],'Náhuatl','Muchas palabras mexicanas proceden del náhuatl.'],
['🌎 Geografía','¿En qué continente se encuentra México?',['América','Europa','Asia','África'],'América','México está en América del Norte.'],
['🌎 Geografía','¿Cuál es el océano más grande de la Tierra?',['Pacífico','Atlántico','Índico','Ártico'],'Pacífico','El Pacífico es el más extenso.'],
['🌎 Geografía','¿Cuál es la capital de México?',['Ciudad de México','Guadalajara','Monterrey','Puebla'],'Ciudad de México','La capital es Ciudad de México.'],
['🌎 Geografía','¿Qué país está al norte de México?',['Estados Unidos','Brasil','Argentina','España'],'Estados Unidos','Comparte frontera norte con México.'],
['🌎 Geografía','¿Cuál es el continente más grande?',['Asia','Europa','Oceanía','Antártida'],'Asia','Asia es el continente de mayor superficie.'],
['🌎 Geografía','¿Qué línea imaginaria divide la Tierra en hemisferio norte y sur?',['Ecuador','Meridiano de Greenwich','Trópico de Cáncer','Círculo Polar'],'Ecuador','El ecuador está a 0° de latitud.'],
['🌎 Geografía','¿En qué continente está Egipto?',['África','Asia','Europa','América'],'África','La mayor parte de Egipto está en África.'],
['🔭 Ciencia','¿Cuál es el planeta más cercano al Sol?',['Mercurio','Venus','Tierra','Marte'],'Mercurio','Mercurio es el primer planeta.'],
['🔭 Ciencia','¿Qué planeta es conocido como el planeta rojo?',['Marte','Venus','Júpiter','Neptuno'],'Marte','Su superficie tiene un tono rojizo.'],
['🔭 Ciencia','¿Cuál es el planeta más grande del Sistema Solar?',['Júpiter','Saturno','Tierra','Marte'],'Júpiter','Júpiter es el mayor.'],
['🔭 Ciencia','¿Cómo se llama la estrella de nuestro sistema?',['Sol','Luna','Sirio','Marte'],'Sol','El Sol es nuestra estrella.'],
['🌿 Ciencia','¿Qué gas necesita el cuerpo principalmente para respirar?',['Oxígeno','Helio','Hidrógeno','Neón'],'Oxígeno','Usamos oxígeno en la respiración celular.'],
['🌿 Ciencia','¿Qué órgano bombea la sangre por el cuerpo?',['Corazón','Pulmón','Estómago','Riñón'],'Corazón','El corazón impulsa la sangre.'],
['🌿 Ciencia','¿Qué parte de la planta absorbe principalmente agua del suelo?',['Raíz','Flor','Fruto','Hoja'],'Raíz','Las raíces absorben agua y minerales.'],
['🐾 Ciencia','¿Cuál de estos animales es mamífero?',['Delfín','Tiburón','Pulpo','Tortuga'],'Delfín','El delfín es mamífero.'],
['🐾 Ciencia','¿Cuál de estos animales es anfibio?',['Rana','Águila','Gato','Tiburón'],'Rana','La rana es un anfibio.'],
['🌿 Ciencia','¿Qué fuerza hace caer los objetos al suelo?',['Gravedad','Magnetismo','Electricidad','Fricción'],'Gravedad','La gravedad atrae los cuerpos.'],
['🔤 Lenguaje','¿Cuál palabra está escrita correctamente?',['Árbol','Arvol','Hárbol','Árvol'],'Árbol','Árbol se escribe con b y tilde.'],
['🔤 Lenguaje','¿Cuál palabra es un verbo?',['Correr','Mesa','Azul','Rápido'],'Correr','Correr expresa una acción.'],
['🔤 Lenguaje','¿Cuál palabra es un sustantivo?',['Casa','Saltar','Bonito','Rápidamente'],'Casa','Casa nombra un objeto o lugar.'],
['🔤 Lenguaje','¿Cuál signo abre una pregunta en español?',['¿','?','¡','!'],'¿','Las preguntas usan signo de apertura y cierre.'],
['🔤 Lenguaje','¿Cuál es un sinónimo de “feliz”?',['Alegre','Triste','Oscuro','Lento'],'Alegre','Alegre tiene un significado parecido.'],
['🔤 Lenguaje','¿Cuál es el antónimo de “grande”?',['Pequeño','Enorme','Amplio','Gigante'],'Pequeño','Pequeño expresa lo contrario.'],
['🧠 Lógica','Completa: 2, 4, 6, 8, ...',['10','9','11','12'],'10','Aumenta de dos en dos.'],
['🧠 Lógica','Completa: 5, 10, 15, 20, ...',['25','22','30','21'],'25','Aumenta de cinco en cinco.'],
['🧠 Lógica','🐶 🐱 🐶 🐱 🐶 ... ¿qué sigue?',['🐱','🐶','🐭','🐰'],'🐱','Alterna perro y gato.'],
['🧠 Lógica','Si hoy es martes, ¿qué día será dentro de dos días?',['Jueves','Miércoles','Viernes','Domingo'],'Jueves','Dos días después es jueves.'],
['🧠 Lógica','Ana es más alta que Luis y Luis más alto que Leo. ¿Quién es más alto?',['Ana','Luis','Leo','Todos igual'],'Ana','Ana supera a ambos.'],
['🎨 Cultura general','¿Qué color se obtiene al mezclar azul y amarillo?',['Verde','Rojo','Morado','Negro'],'Verde','Azul y amarillo forman verde en pigmentos.'],
['📚 Cultura general','¿Quién escribió “Don Quijote de la Mancha”?',['Miguel de Cervantes','Gabriel García Márquez','Octavio Paz','William Shakespeare'],'Miguel de Cervantes','Cervantes es su autor.'],
['🌍 Cultura general','¿Cuántos días tiene una semana?',['7','5','6','8'],'7','Una semana tiene siete días.'],
['🌍 Cultura general','¿Cuántos meses tiene un año?',['12','10','11','13'],'12','Un año tiene doce meses.'],
['🌍 Cultura general','¿Cuál es el satélite natural de la Tierra?',['La Luna','Marte','El Sol','Venus'],'La Luna','La Luna orbita la Tierra.'],
['🌍 Cultura general','¿Qué objeto sirve para orientarse con puntos cardinales?',['Brújula','Termómetro','Regla','Microscopio'],'Brújula','La brújula indica direcciones.']
].map(x=>({cat:x[0],q:x[1],opts:x[2],a:x[3],e:x[4]}));
function numOpts(ans){const v=new Set([ans,Math.max(0,ans-1),ans+1,Math.max(0,ans-2)]);return[...v].slice(0,4).map(String)}
function mathBank(level){const out=[];for(let i=1;i<=25;i++){if(level==='small'){let a=i%15+2,b=(i*3)%9+1;out.push({cat:'➕ Matemáticas',q:`¿Cuánto es ${a} + ${b}?`,opts:numOpts(a+b),a:String(a+b),e:`${a} + ${b} = ${a+b}.`})}else if(level==='medium'){let a=i%9+2,b=(i*3)%10+2,z=a*b;out.push({cat:'✖️ Matemáticas',q:`¿Cuánto es ${a} × ${b}?`,opts:numOpts(z),a:String(z),e:`${a} × ${b} = ${z}.`})}else{let a=i*4+12,b=i%8+2,z=a*b;out.push({cat:'➗ Matemáticas',q:`¿Cuánto es ${z} ÷ ${b}?`,opts:numOpts(a),a:String(a),e:`${z} ÷ ${b} = ${a}.`})}}for(let i=1;i<=18;i++){let a=i*9+(level==='small'?10:100),b=i*5+(level==='small'?5:80),m=Math.max(a,b);out.push({cat:'🔍 Comparación',q:`¿Qué número es mayor: ${a} o ${b}?`,opts:[String(a),String(b),'Son iguales','No se puede saber'],a:String(m),e:`${m} es el mayor.`})}return out}
const levelExtras={small:[{cat:'📐 Figuras',q:'¿Qué figura tiene tres lados?',opts:['Triángulo','Cuadrado','Círculo','Rectángulo'],a:'Triángulo',e:'El triángulo tiene tres lados.'},{cat:'🔤 Lenguaje',q:'¿Con qué letra comienza “mariposa”?',opts:['M','P','R','S'],a:'M',e:'Mariposa comienza con M.'},{cat:'🔤 Lenguaje',q:'¿Cuál palabra rima con “gato”?',opts:['Pato','Mesa','Sol','Luna'],a:'Pato',e:'Gato y pato riman.'}],medium:[{cat:'📐 Matemáticas',q:'Un cuadrado tiene lado de 4 cm. ¿Cuál es su perímetro?',opts:['16 cm','8 cm','12 cm','20 cm'],a:'16 cm',e:'4+4+4+4=16.'},{cat:'🕒 Tiempo',q:'¿Cuántos minutos hay en 2 horas?',opts:['120','60','90','200'],a:'120',e:'2×60=120.'},{cat:'🔤 Lenguaje',q:'¿Cuál palabra es esdrújula?',opts:['Música','Canción','Papel','Reloj'],a:'Música',e:'Mú-si-ca es esdrújula.'}],big:[{cat:'🔢 Matemáticas',q:'¿Cuál es el 25% de 200?',opts:['50','25','75','100'],a:'50',e:'25% es una cuarta parte.'},{cat:'🔭 Ciencia',q:'¿Qué proceso usan las plantas para fabricar alimento con luz?',opts:['Fotosíntesis','Respiración','Evaporación','Digestión'],a:'Fotosíntesis',e:'Ese proceso es la fotosíntesis.'},{cat:'🌎 Geografía',q:'¿Qué coordenada indica distancia al norte o sur del ecuador?',opts:['Latitud','Longitud','Altitud','Profundidad'],a:'Latitud',e:'La latitud se mide desde el ecuador.'}]};
let state=freshState(),questionQueue=[],activeWrongAttempts=0;
function freshState(){return{name:'',avatar:selectedAvatar,level:'medium',pos:1,score:0,correct:0,answered:0,wrong:0,streak:0,bestStreak:0,memoryCorrect:0,memoryAsked:0,challengeIndex:0,memories:{},finished:false,usedQuestions:[],currentQuestion:null}}
function shuffled(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function buildQueue(){const used=new Set(state.usedQuestions||[]),bank=[...fixed,...mathBank(state.level),...(levelExtras[state.level]||[])];questionQueue=shuffled(bank.filter(q=>!used.has(q.q)))}
function nextQ(){if(state.currentQuestion)return state.currentQuestion;if(!questionQueue.length)buildQueue();while(questionQueue.length){let q=questionQueue.shift();if(!state.usedQuestions.includes(q.q)){state.currentQuestion=q;state.usedQuestions.push(q.q);save();return q}}return null}
function buildAvatars(){$('#avatars').innerHTML=avatars.map((a,i)=>`<button class="avatar ${i?'':'active'}" data-a="${a}">${a}</button>`).join('');document.querySelectorAll('.avatar').forEach(b=>b.onclick=()=>{document.querySelectorAll('.avatar').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedAvatar=b.dataset.a})}
function buildBoard(){let b=$('#board');b.innerHTML='';let rows=[];for(let r=0;r<8;r++){let s=36-r*5,row=[s,s+1,s+2,s+3,s+4];if(r%2===0)row.reverse();rows.push(row)}rows.flat().forEach(n=>{let c=document.createElement('div');c.className='cell'+(ladders[n]?' special-ladder':'')+(snakes[n]?' special-snake':'')+(n===40?' finish':'');c.dataset.n=n;c.innerHTML=`<span>${n}</span>${ladders[n]?'<span class="mini">🪜</span>':''}${snakes[n]?'<span class="mini">🐍</span>':''}${n===40?'<span class="mini">🏆</span>':''}`;b.appendChild(c)});updateToken()}
function updateToken(){document.querySelectorAll('.cell').forEach(c=>{c.classList.remove('current');c.querySelector('.token')?.remove()});let v=Math.max(1,Math.min(40,state.pos)),c=document.querySelector(`.cell[data-n="${v}"]`);if(c){c.classList.add('current');let t=document.createElement('div');t.className='token';t.textContent=state.avatar;c.appendChild(t)}$('#posLabel').textContent=state.pos<1?`DEUDA ${1-state.pos}`:state.pos;$('#scoreLabel').textContent=state.score;$('#streakLabel').textContent=state.streak;$('#progressBar').style.width=`${Math.max(2,Math.max(1,state.pos)/40*100)}%`;updateWorld();save()}
function updateWorld(){let p=Math.max(1,state.pos),w='🌿 Selva del Inicio';if(p>=9)w='🏺 Ruinas del Tiempo';if(p>=17)w='🌋 Paso del Volcán';if(p>=25)w='🔭 Observatorio Secreto';if(p>=33)w='🏰 Fortaleza del Tesoro';if(state.pos<1)w=`⛓️ Zona de deuda: debes ${1-state.pos} casillas`;$('#worldName').textContent=w;$('#missionLabel').textContent=`Misión ${state.challengeIndex+1} · ${state.usedQuestions.length} preguntas distintas`}
function toast(m){let t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function save(){localStorage.setItem('tesoroExpedicionV2',JSON.stringify(state))}
function start(){let n=$('#playerName').value.trim();if(!n)return toast('Escribe tu nombre o apodo.');state=freshState();state.name=n;state.avatar=selectedAvatar;state.level=$('#level').value;buildQueue();$('#topAvatar').textContent=state.avatar;$('#topName').textContent=n;$('#miniPlayerName').textContent=n;$('#startScreen').classList.remove('active');$('#gameScreen').classList.add('active');buildBoard()}
function missionType(i){const stores={2:0,10:1,19:2,28:3,37:4,46:5},recalls={7:0,16:1,25:2,34:3,43:4,52:5};if(stores[i]!==undefined)return['store',stores[i]];if(recalls[i]!==undefined)return['recall',recalls[i]];return['q',null]}
function openChallenge(){if(state.finished)return;let[t,i]=missionType(state.challengeIndex);if(t==='store')return showMemoryStore(i);if(t==='recall')return renderQuestion(memoryDeck[i].recall,true);let q=nextQ();if(!q)return toast('Ya resolviste todo el banco disponible.');renderQuestion(q,false)}
function renderQuestion(q,isMemory){activeWrongAttempts=0;let opts=shuffled(q.opts);$('#sheet').innerHTML=`<span class="qtag">${isMemory?'🧠 Memoria':q.cat}</span><h3 class="question" id="questionTitle">${q.q}</h3><div class="context">${isMemory?'Recuerda lo que viste varios retos antes. ':''}<b>Debes acertar.</b> Cada error aumenta el retroceso.</div><div class="options">${opts.map((o,i)=>`<button class="option" data-value="${esc(o)}"><span><b>${String.fromCharCode(65+i)}.</b> ${o}</span><span>›</span></button>`).join('')}</div><div class="feedback" id="feedback"></div><button class="continue" id="continueBtn">Continuar en el mapa →</button>`;$('#challengeModal').classList.add('show');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(b,q,isMemory))}
function answer(btn,q,isMemory){if(btn.disabled)return;let correct=btn.dataset.value===q.a,fb=$('#feedback');state.answered++;if(!correct){activeWrongAttempts++;state.wrong++;state.streak=0;let pen=activeWrongAttempts*2;state.pos-=pen;state.score-=pen*10;btn.classList.add('wrong');btn.disabled=true;fb.className='feedback show no';fb.innerHTML=`🐍 <b>Error ${activeWrongAttempts}:</b> retrocedes <b>${pen}</b> casillas.${state.pos<1?` Tienes <b>${1-state.pos} de deuda</b>.`:''}<br>Inténtalo otra vez. El siguiente error costará ${pen+2}.`;updateToken();return}btn.classList.add('correct');document.querySelectorAll('.option').forEach(b=>{b.disabled=true;b.classList.add('locked')});state.correct++;state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak);if(isMemory){state.memoryCorrect++;state.memoryAsked++}let gain=isMemory?180:120;state.score+=gain;fb.className='feedback show ok';fb.innerHTML=`✅ <b>¡Correcto!</b> El castigo se detiene. +${gain} puntos. ${q.e||''}`;$('#continueBtn').classList.add('show');$('#continueBtn').onclick=()=>{$('#challengeModal').classList.remove('show');state.currentQuestion=null;state.challengeIndex++;moveBy(isMemory?4:3,`✨ +${isMemory?4:3} casillas`)};save()}
function showMemoryStore(i){let m=memoryDeck[i];$('#sheet').innerHTML=`<span class="qtag">👁️ Observación</span><h3 class="question">Guarda esta pista en tu memoria</h3><div class="memory-stage"><p style="color:var(--muted)">${m.prompt}</p><div class="memory-grid">${m.items.map(x=>`<div class="memory-item"><div class="num" style="color:${x[1]}">${x[0]}</div></div>`).join('')}</div><div class="memory-timer"><i></i></div><p style="font-size:.8rem;color:#9eb1d4">Desaparecerá en 6 segundos…</p></div>`;$('#challengeModal').classList.add('show');setTimeout(()=>{$('#sheet').innerHTML=`<span class="qtag">🧠 Pista guardada</span><h3 class="question">¡Listo!</h3><div class="context">No te diré cuándo volverá.</div><button class="continue show" id="continueMemory">Regresar al mapa →</button>`;$('#continueMemory').onclick=()=>{$('#challengeModal').classList.remove('show');state.challengeIndex++;moveBy(2,'👁️ +2 casillas')}},6100)}
function moveBy(n,msg){let target=Math.min(40,state.pos+n),cur=state.pos;if(cur===target)return afterMove(msg);let timer=setInterval(()=>{cur++;state.pos=cur;updateToken();if(cur>=target){clearInterval(timer);setTimeout(()=>afterMove(msg),180)}},100)}
function afterMove(msg){if(state.pos>=1&&ladders[state.pos]){let f=state.pos;state.pos=ladders[f];state.score+=50;updateToken();toast(`🪜 ${f} → ${state.pos}`)}else if(state.pos>=1&&snakes[state.pos]){let f=state.pos;state.pos=snakes[f];state.score-=30;updateToken();toast(`🐍 ${f} → ${state.pos}`)}else toast(msg);if(state.pos>=40)return setTimeout(finish,700);prepareNext()}
function prepareNext(){let[t]=missionType(state.challengeIndex);$('#cardTitle').textContent=t==='store'?'👁️ Cámara de observación':t==='recall'?'🧠 El templo recuerda':['Una puerta antigua','El puente del conocimiento','La brújula pregunta','Una inscripción misteriosa'][state.challengeIndex%4];$('#cardText').textContent=state.pos<1?`Debes ${1-state.pos} casillas. Acierta para recuperarlas.`:'Debes acertar. Cada error consecutivo aumenta el retroceso.';$('#cardEyebrow').textContent=`Misión ${state.challengeIndex+1}`;updateWorld()}
function finish(){state.finished=true;state.pos=40;$('#gameScreen').classList.remove('active');$('#resultScreen').classList.add('active');let mp=state.memoryAsked?Math.round(state.memoryCorrect/state.memoryAsked*100):0;$('#finalScore').textContent=state.score;$('#finalCorrect').textContent=`${state.correct}/${state.answered}`;$('#finalMemory').textContent=mp+'%';$('#finalStreak').textContent=state.bestStreak;$('#finalPos').textContent='40';$('#resultMessage').textContent=`${state.name}, llegaste al tesoro con ${state.usedQuestions.length} preguntas distintas y ${state.wrong} errores acumulados.`;$('#secretCode').textContent=code();save()}
function code(){let a=['JAGUAR','QUETZAL','AXOLOTE','PUMA','AGUILA'],n=(Math.abs(state.score)+state.correct*17+state.name.length*31)%900+100;return`${a[state.name.length%a.length]}-${n}`}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
$('#startBtn').onclick=start;$('#challengeBtn').onclick=openChallenge;$('#copyBtn').onclick=async()=>{let x=`🏆 ${state.name} completó El Tesoro Perdido con ${state.score} puntos. Código: ${$('#secretCode').textContent}`;try{await navigator.clipboard.writeText(x);toast('Resultado copiado.')}catch{toast('Mantén presionado el código para copiarlo.')}};$('#restartBtn').onclick=()=>{localStorage.removeItem('tesoroExpedicionV2');location.reload()};
function restore(){let raw=localStorage.getItem('tesoroExpedicionV2');if(!raw)return;try{state={...freshState(),...JSON.parse(raw)};if(!state.name)return;if(state.finished){$('#startScreen').classList.remove('active');$('#resultScreen').classList.add('active');$('#finalScore').textContent=state.score;$('#finalCorrect').textContent=`${state.correct}/${state.answered}`;$('#finalMemory').textContent=(state.memoryAsked?Math.round(state.memoryCorrect/state.memoryAsked*100):0)+'%';$('#finalStreak').textContent=state.bestStreak;$('#finalPos').textContent='40';$('#resultMessage').textContent=`${state.name}, completaste la expedición.`;$('#secretCode').textContent=code();return}state.currentQuestion=null;buildQueue();$('#startScreen').classList.remove('active');$('#gameScreen').classList.add('active');$('#topAvatar').textContent=state.avatar;$('#topName').textContent=state.name;$('#miniPlayerName').textContent=state.name;buildBoard();prepareNext();toast('🧭 Expedición recuperada.')}catch(e){localStorage.removeItem('tesoroExpedicionV2')}}
buildAvatars();restore();